Repository Ativos-Tecnologia/ativos-cvld-front, pull requests merged in 2025-01, with the labels that each got.

#1072 Cria componentes GoalChart e GoalChartCard
  package-lock.json
  src/components/Charts/GoalChart.tsx
  src/components/Features/Comercial/GoalChartCard.tsx
Labels: feature, front-end

#1085 ♻️ Adiciona target blank para tags <a> e <Link />
  src/app/automated-proposal/page.tsx
  src/app/comercial/resumo/columns.tsx
  src/app/pricing/page.tsx
  src/components/Drawer/Drawer.tsx
  src/components/Header/Balance.tsx
  src/components/Header/DropdownUser.tsx
  src/components/Header/UnloggedHeader.tsx
  src/components/Juridico/Details.tsx
  src/components/Modals/BrokersDocs/ShowDocs.tsx
  src/components/ResultCVLD/index.tsx
Labels: front-end

#1093 Gráfico de barras responsável por mostrar o valor liquido total a ser cedido
  src/components/Charts/TotalAvailableLiquidChart.tsx
  src/components/Features/Comercial/GoalChartCard.tsx
  src/components/Skeletons/TotalLiquidAvailableChartSkeleton.tsx
  src/functions/charts/generateColor.ts
  src/functions/charts/groupResultsByUsuario.ts
Labels: enhancement

#1097 ✨ Input com máscara de CPF e CNPJ
  src/components/CrmUi/CPFAndCNPFInput/index.tsx
  src/functions/formaters/CPFAndCNPJInput.ts
Labels: front-end

#1100 Refactor estilos e funções auxiliares
  src/components/Charts/TotalAvailableLiquidChart.tsx
  src/components/Features/Comercial/EspacoGerencial.tsx
  src/components/Features/Comercial/GoalChartCard.tsx
  src/components/Skeletons/ComercialBrokersChartSkeleton.tsx
  src/components/Skeletons/GoalChartSkeleton.tsx
  src/components/Skeletons/TotalLiquidAvailableChartSkeleton.tsx
  src/functions/charts/generateColor.ts
Labels: front-end

#1106 Adiciona funcionalidade para gerar PDF da proposta no SheetViewComercial e ajusta o grid da proposta.
  src/components/Features/Comercial/SheetViewComercial.tsx
  src/components/ui/sheet.tsx
Labels: bug, feature, front-end

#1115 Implementa componente CPFAndCNPJInput
  src/app/auth/signup/page.tsx
  src/components/CrmUi/CPFAndCNPFInput/index.tsx
  src/components/Forms/CalcForm.tsx
  src/components/Forms/EditOficioBrokerForm.tsx
  src/components/MainForm/index.tsx
  src/components/Modals/NewForm.tsx
  src/functions/verifiers/isCPFOrCNPJValid.ts
Labels: front-end

#1129 Mudancas visuais e tema claro
  src/components/Charts/CommissionParticipationChart.tsx
  src/components/Features/Comercial/EspacoGerencial.tsx
  src/components/Features/Comercial/SheetViewComercial.tsx
Labels: front-end

#1139 Responsividade para SheetViewComercial
  src/components/Charts/ComercialUserVsStatusChart.tsx
  src/components/Charts/CommissionParticipationChart.tsx
  src/components/Features/Comercial/EspacoGerencial.tsx
  src/components/Features/Comercial/SheetViewComercial.tsx
Labels: front-end

#1144 Ordenação dos dados do ComercialUserVsStatusChart
  src/components/Charts/ComercialUserVsStatusChart.tsx
Labels: front-end

#1154 :art: REFACT: exibição dos dados da SheetViewComercial
  src/components/Features/Comercial/SheetViewComercial.tsx
Labels: front-end

#1161 🔧 Fix estilos e dados signup / broker
  src/app/auth/signup/page.tsx
  src/components/Charts/BrokerQuantityDistributedChart.tsx
  src/components/Forms/CalcForm.tsx
Labels: front-end
